version: "3.8"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    platform: linux/amd64
    depends_on:
      - db
    environment:
      DATABASE_ADMIN_USERNAME: postgres
      DATABASE_ADMIN_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: nlcommons
      DATABASE_PASSWORD: nlcommons
      DATABASE_NAME: nlcommons_development
      RUN_DB_SETUP: "true"
      RAILS_ENV: development
      RACK_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  pgdata:
